// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaAeq60p6IUr9rBzyD9d_0fbakEg6P9jM',
    appId: '1:953136898217:web:77c1cc4362a948a75b49b8',
    messagingSenderId: '953136898217',
    projectId: 'guardiantag-466c9',
    authDomain: 'guardiantag-466c9.firebaseapp.com',
    storageBucket: 'guardiantag-466c9.appspot.com',
    measurementId: 'G-FP1SE37S6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7MLnpiSdHZaZBogUusaCa-waFq7v_B_Q',
    appId: '1:953136898217:android:562cafb27d7b853d5b49b8',
    messagingSenderId: '953136898217',
    projectId: 'guardiantag-466c9',
    storageBucket: 'guardiantag-466c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOzAArHxJzH6iQQYKgHZjHy67-_bXs-q0',
    appId: '1:953136898217:ios:a9942ce4823721ed5b49b8',
    messagingSenderId: '953136898217',
    projectId: 'guardiantag-466c9',
    storageBucket: 'guardiantag-466c9.appspot.com',
    iosBundleId: 'com.example.googleMapsYt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOzAArHxJzH6iQQYKgHZjHy67-_bXs-q0',
    appId: '1:953136898217:ios:a9942ce4823721ed5b49b8',
    messagingSenderId: '953136898217',
    projectId: 'guardiantag-466c9',
    storageBucket: 'guardiantag-466c9.appspot.com',
    iosBundleId: 'com.example.googleMapsYt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaAeq60p6IUr9rBzyD9d_0fbakEg6P9jM',
    appId: '1:953136898217:web:46604059c1493ea55b49b8',
    messagingSenderId: '953136898217',
    projectId: 'guardiantag-466c9',
    authDomain: 'guardiantag-466c9.firebaseapp.com',
    storageBucket: 'guardiantag-466c9.appspot.com',
    measurementId: 'G-XW8S085VNC',
  );
}
